### ISSUE TITLE
Using Docker (Rocker) to check packages on a fresh install

### ISSUE THREAD

**Issue by dill** [davharris/cran_guide#1]
[Ted Hart](https://twitter.com/emhrt_) put together some useful instructions on using Docker (or more correctly Rocker) to test packages. This is potentially useful if you want to check what will happen on a "fresh" (Linux) install of R with other package versions all from CRAN (which can be problematic if you have patched/github versions of packages on your machine but don't remember).

Ted's article:

[Docker and R: making CRAN submission a little easier](http://emhart.info/blog/2015/04/07/docker-r/)

(The comments are also useful.)

**Comment by davharris** [comment]
Thanks, added the link!
